version: "3.7"

services:
  php-fpm-nginx:
    build: ./docker/php-fpm-nginx
    volumes:
      - ./:/var/www/app:cached
      - ./docker/php-fpm-nginx/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./docker/php-fpm-nginx/www.conf:/etc/php7/php-fpm.d/www.conf:ro
      - ./docker/php-fpm-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/php-fpm-nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8001:80
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025
